"""init

Revision ID: b185a6588940
Revises: 
Create Date: 2026-09-22 19:57:13.308502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b185a6588940'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'teacher', 'student', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'indexed', 'failed', name='materialstatus', native_enum=False, length=32), nullable=False),
    sa.Column('chroma_collection', sa.String(length=128), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_materials_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_index(op.f('ix_materials_content_hash'), 'materials', ['content_hash'], unique=False)
    op.create_index(op.f('ix_materials_owner_id'), 'materials', ['owner_id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_time_limit_sec', sa.Integer(), server_default='30', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('google_form_id', sa.String(length=128), nullable=True),
    sa.Column('google_form_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tests_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tests'))
    )
    op.create_index(op.f('ix_tests_owner_id'), 'tests', ['owner_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('verified_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_generation_jobs_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_generation_jobs_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs'))
    )
    op.create_index(op.f('ix_generation_jobs_test_id'), 'generation_jobs', ['test_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('single_choice', 'multiple_choice', 'true_false', name='questiontype', native_enum=False, length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ai_rejected', 'ai_verified', 'approved', 'archived', name='questionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('origin', sa.Enum('ai_generated', 'ai_modified', 'manual', name='questionorigin', native_enum=False, length=32), nullable=False),
    sa.Column('points', sa.Float(), server_default='1', nullable=False),
    sa.Column('time_limit_sec', sa.Integer(), nullable=True),
    sa.Column('source_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('generation_attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('irt_discrimination', sa.Float(), nullable=True),
    sa.Column('irt_difficulty', sa.Float(), nullable=True),
    sa.Column('irt_guessing', sa.Float(), nullable=True),
    sa.Column('irt_calibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['questions.id'], name=op.f('fk_questions_parent_id_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_questions_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_parent_id'), 'questions', ['parent_id'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_index(op.f('ix_questions_test_id'), 'questions', ['test_id'], unique=False)
    op.create_table('test_materials',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_test_materials_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_materials_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', 'material_id', name=op.f('pk_test_materials'))
    )
    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('pin_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('lobby', 'running', 'finished', 'cancelled', name='sessionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('fk_test_sessions_host_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_sessions_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_sessions'))
    )
    op.create_index(op.f('ix_test_sessions_host_id'), 'test_sessions', ['host_id'], unique=False)
    op.create_index(op.f('ix_test_sessions_test_id'), 'test_sessions', ['test_id'], unique=False)
    op.create_index('uq_test_sessions_active_pin', 'test_sessions', ['pin_code'], unique=True, postgresql_where=sa.text("status IN ('lobby', 'running')"))
    op.create_table('answer_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('distractor_rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answer_options_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_options'))
    )
    op.create_index(op.f('ix_answer_options_question_id'), 'answer_options', ['question_id'], unique=False)
    op.create_table('question_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('passed', 'failed', name='verificationverdict', native_enum=False, length=32), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('critique', sa.Text(), nullable=True),
    sa.Column('critic_model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_verifications_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_verifications'))
    )
    op.create_index(op.f('ix_question_verifications_question_id'), 'question_verifications', ['question_id'], unique=False)
    op.create_table('session_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('reconnect_token', sa.String(length=64), nullable=False),
    sa.Column('is_connected', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], name=op.f('fk_session_participants_session_id_test_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_participants_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_participants')),
    sa.UniqueConstraint('reconnect_token', name=op.f('uq_session_participants_reconnect_token')),
    sa.UniqueConstraint('session_id', 'display_name', name=op.f('uq_session_participants_session_id_display_name'))
    )
    op.create_index(op.f('ix_session_participants_session_id'), 'session_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_participants_user_id'), 'session_participants', ['user_id'], unique=False)
    op.create_table('proctoring_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('distraction_warning', 'face_not_detected', 'multiple_faces', 'tab_hidden', 'fullscreen_exit', name='proctoringeventtype', native_enum=False, length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['session_participants.id'], name=op.f('fk_proctoring_events_participant_id_session_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_proctoring_events_question_id_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], name=op.f('fk_proctoring_events_session_id_test_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proctoring_events'))
    )
    op.create_index(op.f('ix_proctoring_events_participant_id'), 'proctoring_events', ['participant_id'], unique=False)
    op.create_index(op.f('ix_proctoring_events_session_id'), 'proctoring_events', ['session_id'], unique=False)
    op.create_table('student_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('had_distraction', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['session_participants.id'], name=op.f('fk_student_answers_participant_id_session_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_student_answers_question_id_questions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], name=op.f('fk_student_answers_session_id_test_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_answers')),
    sa.UniqueConstraint('participant_id', 'question_id', name=op.f('uq_student_answers_participant_id_question_id'))
    )
    op.create_index(op.f('ix_student_answers_participant_id'), 'student_answers', ['participant_id'], unique=False)
    op.create_index(op.f('ix_student_answers_question_id'), 'student_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_student_answers_session_id'), 'student_answers', ['session_id'], unique=False)
    op.create_table('student_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('answered_count', sa.Integer(), nullable=False),
    sa.Column('distraction_count', sa.Integer(), nullable=False),
    sa.Column('ability_theta', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['session_participants.id'], name=op.f('fk_student_results_participant_id_session_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], name=op.f('fk_student_results_session_id_test_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_results')),
    sa.UniqueConstraint('participant_id', name=op.f('uq_student_results_participant_id'))
    )
    op.create_index(op.f('ix_student_results_session_id'), 'student_results', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_results_session_id'), table_name='student_results')
    op.drop_table('student_results')
    op.drop_index(op.f('ix_student_answers_session_id'), table_name='student_answers')
    op.drop_index(op.f('ix_student_answers_question_id'), table_name='student_answers')
    op.drop_index(op.f('ix_student_answers_participant_id'), table_name='student_answers')
    op.drop_table('student_answers')
    op.drop_index(op.f('ix_proctoring_events_session_id'), table_name='proctoring_events')
    op.drop_index(op.f('ix_proctoring_events_participant_id'), table_name='proctoring_events')
    op.drop_table('proctoring_events')
    op.drop_index(op.f('ix_session_participants_user_id'), table_name='session_participants')
    op.drop_index(op.f('ix_session_participants_session_id'), table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_index(op.f('ix_question_verifications_question_id'), table_name='question_verifications')
    op.drop_table('question_verifications')
    op.drop_index(op.f('ix_answer_options_question_id'), table_name='answer_options')
    op.drop_table('answer_options')
    op.drop_index('uq_test_sessions_active_pin', table_name='test_sessions', postgresql_where=sa.text("status IN ('lobby', 'running')"))
    op.drop_index(op.f('ix_test_sessions_test_id'), table_name='test_sessions')
    op.drop_index(op.f('ix_test_sessions_host_id'), table_name='test_sessions')
    op.drop_table('test_sessions')
    op.drop_table('test_materials')
    op.drop_index(op.f('ix_questions_test_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_parent_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_generation_jobs_test_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_tests_owner_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_materials_owner_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_content_hash'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
